"""
Tests that load before/after .h5 fixtures for every rule and verify that the
implemented transform (where applicable) produces the expected after-state.

Fixtures are auto-generated by tests/fixtures/create_fixtures.py if absent.
"""
from __future__ import annotations

import os
from pathlib import Path

import numpy as np
import pytest
import tensorflow as tf

FIXTURES_DIR = Path(__file__).parent / "fixtures"


# ---------------------------------------------------------------------------
# Session-scoped fixture: ensure all .h5 fixture files exist
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session", autouse=True)
def ensure_fixtures():
    """Generate .h5 fixtures if any are missing."""
    import importlib.util, sys
    script = FIXTURES_DIR / "create_fixtures.py"
    spec = importlib.util.spec_from_file_location("create_fixtures", script)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    mod.create_all(force=False)


def _load(rule_id: str, state: str) -> tf.keras.Model:
    path = FIXTURES_DIR / rule_id / f"{state}.h5"
    assert path.exists(), f"Fixture missing: {path}"
    return tf.keras.models.load_model(str(path), compile=False)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _layer_types(model: tf.keras.Model) -> list[str]:
    return [type(l).__name__ for l in model.layers]


def _activation_of(layer) -> str:
    cfg = layer.get_config()
    act = cfg.get("activation", "linear")
    if isinstance(act, dict):
        act = act.get("class_name", "linear")
    return str(act).lower()


def _global_sparsity(model: tf.keras.Model) -> float:
    total, zeros = 0, 0
    for layer in model.layers:
        for w in layer.get_weights():
            total += w.size
            zeros += int(np.sum(w == 0))
    return zeros / total if total > 0 else 0.0


def _unique_weight_values(model: tf.keras.Model) -> int:
    vals = set()
    for layer in model.layers:
        for w in layer.get_weights():
            vals.update(np.unique(w).tolist())
    return len(vals)


# ---------------------------------------------------------------------------
# RULE-L01 — Channel alignment
# ---------------------------------------------------------------------------

class TestRuleL01:
    def test_before_has_misaligned_channels(self):
        m = _load("RULE-L01", "before")
        conv = m.get_layer("conv1")
        assert conv.filters % 16 != 0

    def test_after_has_aligned_channels(self):
        m = _load("RULE-L01", "after")
        conv = m.get_layer("conv1")
        assert conv.filters % 16 == 0

    def test_transform_aligns_channels(self):
        from optimizer.transforms import align_channels
        before = _load("RULE-L01", "before")
        transformed = align_channels(before)
        conv = transformed.get_layer("conv1")
        assert conv.filters % 16 == 0


# ---------------------------------------------------------------------------
# RULE-L02 — INT8 quantization (structural detection)
# ---------------------------------------------------------------------------

class TestRuleL02:
    def test_before_fixture_loads(self):
        _load("RULE-L02", "before")

    def test_after_fixture_loads(self):
        _load("RULE-L02", "after")

    def test_before_weights_are_float32(self):
        m = _load("RULE-L02", "before")
        for layer in m.layers:
            for w in layer.get_weights():
                assert w.dtype in (np.float32, np.float16), (
                    f"Expected float weights on {layer.name}, got {w.dtype}"
                )


# ---------------------------------------------------------------------------
# RULE-L03 — Magnitude pruning
# ---------------------------------------------------------------------------

class TestRuleL03:
    def test_after_has_higher_sparsity(self):
        before = _load("RULE-L03", "before")
        after  = _load("RULE-L03", "after")
        assert _global_sparsity(after) > _global_sparsity(before)

    def test_after_sparsity_meets_target(self):
        after = _load("RULE-L03", "after")
        assert _global_sparsity(after) >= 0.60


# ---------------------------------------------------------------------------
# RULE-L04 — K-means clustering
# ---------------------------------------------------------------------------

class TestRuleL04:
    def test_after_has_fewer_unique_values(self):
        before = _load("RULE-L04", "before")
        after  = _load("RULE-L04", "after")
        assert _unique_weight_values(after) < _unique_weight_values(before)


# ---------------------------------------------------------------------------
# RULE-L05 — Unsupported op replacement
# ---------------------------------------------------------------------------

class TestRuleL05:
    def test_before_has_lambda(self):
        m = _load("RULE-L05", "before")
        assert any(type(l).__name__ == "Lambda" for l in m.layers)

    def test_after_has_no_lambda(self):
        m = _load("RULE-L05", "after")
        assert not any(type(l).__name__ == "Lambda" for l in m.layers)


# ---------------------------------------------------------------------------
# RULE-L06 — Activation substitution
# ---------------------------------------------------------------------------

class TestRuleL06:
    def test_before_has_unsupported_activation(self):
        m = _load("RULE-L06", "before")
        conv = m.get_layer("conv1")
        assert _activation_of(conv) == "gelu"

    def test_after_has_supported_activation(self):
        m = _load("RULE-L06", "after")
        conv = m.get_layer("conv1")
        assert _activation_of(conv) in ("relu6", "relu", "linear", "sigmoid", "tanh")

    def test_transform_substitutes_activation(self):
        from optimizer.transforms import substitute_activations
        before = _load("RULE-L06", "before")
        transformed = substitute_activations(before)
        conv = transformed.get_layer("conv1")
        assert _activation_of(conv) != "gelu"


# ---------------------------------------------------------------------------
# RULE-L07 — Depthwise factorization
# ---------------------------------------------------------------------------

class TestRuleL07:
    def test_before_has_conv2d(self):
        m = _load("RULE-L07", "before")
        assert any(isinstance(l, tf.keras.layers.Conv2D) and l.name == "conv3"
                   for l in m.layers)

    def test_after_has_separable_conv(self):
        m = _load("RULE-L07", "after")
        assert any(isinstance(l, tf.keras.layers.SeparableConv2D) and l.name == "conv3"
                   for l in m.layers)

    def test_transform_factorizes_conv(self):
        from optimizer.transforms import factorize_depthwise
        before = _load("RULE-L07", "before")
        transformed = factorize_depthwise(before)
        # conv3 should now be SeparableConv2D
        assert any(isinstance(l, tf.keras.layers.SeparableConv2D) for l in transformed.layers)


# ---------------------------------------------------------------------------
# RULE-C01 — BN foldability
# ---------------------------------------------------------------------------

class TestRuleC01:
    def test_before_has_trainable_bn(self):
        m = _load("RULE-C01", "before")
        bn = m.get_layer("bn1")
        assert bn.trainable

    def test_after_has_frozen_bn(self):
        m = _load("RULE-C01", "after")
        bn = m.get_layer("bn1")
        assert not bn.trainable

    def test_transform_detects_at_risk_bn(self):
        from optimizer.transforms import verify_bn_foldable
        before = _load("RULE-C01", "before")
        at_risk = verify_bn_foldable(before)
        assert "bn1" in at_risk

    def test_frozen_bn_passes_foldability_check(self):
        from optimizer.transforms import verify_bn_foldable
        after = _load("RULE-C01", "after")
        at_risk = verify_bn_foldable(after)
        assert "bn1" not in at_risk


# ---------------------------------------------------------------------------
# RULE-C02 — Conv + BN + ReLU fusion annotation
# ---------------------------------------------------------------------------

class TestRuleC02:
    def test_before_has_separate_bn_relu(self):
        m = _load("RULE-C02", "before")
        types = _layer_types(m)
        assert "BatchNormalization" in types
        assert "ReLU" in types

    def test_after_has_fused_activation(self):
        m = _load("RULE-C02", "after")
        types = _layer_types(m)
        assert "BatchNormalization" not in types
        assert "ReLU" not in types
        conv = m.get_layer("conv1")
        assert _activation_of(conv) == "relu"


# ---------------------------------------------------------------------------
# RULE-C03 — Residual Add alignment
# ---------------------------------------------------------------------------

class TestRuleC03:
    def test_both_fixtures_have_add_layer(self):
        for state in ("before", "after"):
            m = _load("RULE-C03", state)
            assert any(isinstance(l, tf.keras.layers.Add) for l in m.layers)

    def test_transform_reports_no_issues_on_aligned_model(self):
        from optimizer.transforms import check_residual_add_placement
        after = _load("RULE-C03", "after")
        issues = check_residual_add_placement(after)
        assert issues == []


# ---------------------------------------------------------------------------
# RULE-C04 — Dense stack merge
# ---------------------------------------------------------------------------

class TestRuleC04:
    def test_before_has_two_dense_layers(self):
        m = _load("RULE-C04", "before")
        dense_count = sum(1 for l in m.layers if isinstance(l, tf.keras.layers.Dense))
        assert dense_count == 2

    def test_after_has_one_dense_layer(self):
        m = _load("RULE-C04", "after")
        dense_count = sum(1 for l in m.layers if isinstance(l, tf.keras.layers.Dense))
        assert dense_count == 1

    def test_after_output_units_match_second_dense(self):
        """Merged Dense should produce the same number of output units as the original second Dense."""
        before = _load("RULE-C04", "before")
        after  = _load("RULE-C04", "after")
        # Last Dense in before == the only Dense in after.
        before_dense2 = [l for l in before.layers if isinstance(l, tf.keras.layers.Dense)][-1]
        after_dense   = [l for l in after.layers  if isinstance(l, tf.keras.layers.Dense)][0]
        assert before_dense2.units == after_dense.units


# ---------------------------------------------------------------------------
# RULE-C05 — Fused LSTM
# ---------------------------------------------------------------------------

class TestRuleC05:
    def test_after_has_lstm_layer(self):
        m = _load("RULE-C05", "after")
        assert any(isinstance(l, tf.keras.layers.LSTM) for l in m.layers)

    def test_before_has_no_lstm(self):
        m = _load("RULE-C05", "before")
        assert not any(isinstance(l, tf.keras.layers.LSTM) for l in m.layers)


# ---------------------------------------------------------------------------
# RULE-M01 — Global INT8
# ---------------------------------------------------------------------------

class TestRuleM01:
    def test_fixtures_load(self):
        _load("RULE-M01", "before")
        _load("RULE-M01", "after")


# ---------------------------------------------------------------------------
# RULE-M02 — Attention block removal
# ---------------------------------------------------------------------------

class TestRuleM02:
    def test_before_has_attention(self):
        m = _load("RULE-M02", "before")
        assert any(isinstance(l, tf.keras.layers.MultiHeadAttention) for l in m.layers)

    def test_after_has_no_attention(self):
        m = _load("RULE-M02", "after")
        assert not any(isinstance(l, tf.keras.layers.MultiHeadAttention) for l in m.layers)


# ---------------------------------------------------------------------------
# RULE-M03 — Global sparsity
# ---------------------------------------------------------------------------

class TestRuleM03:
    def test_after_higher_sparsity(self):
        before = _load("RULE-M03", "before")
        after  = _load("RULE-M03", "after")
        assert _global_sparsity(after) > _global_sparsity(before)


# ---------------------------------------------------------------------------
# RULE-M04 — First conv channel seeding
# ---------------------------------------------------------------------------

class TestRuleM04:
    def test_before_first_conv_misaligned(self):
        m = _load("RULE-M04", "before")
        conv = m.get_layer("conv1")
        assert conv.filters % 16 != 0

    def test_after_first_conv_aligned(self):
        m = _load("RULE-M04", "after")
        conv = m.get_layer("conv1")
        assert conv.filters % 16 == 0 and conv.filters >= 16

    def test_after_input_channels_unchanged(self):
        """Input spatial shape must be preserved between before and after."""
        before = _load("RULE-M04", "before")
        after  = _load("RULE-M04", "after")
        assert before.input_shape[1:] == after.input_shape[1:]


# ---------------------------------------------------------------------------
# RULE-M05 — Batch size fix
# ---------------------------------------------------------------------------

class TestRuleM05:
    def test_before_has_variable_batch(self):
        m = _load("RULE-M05", "before")
        assert m.input_shape[0] is None

    def test_after_has_fixed_batch(self):
        m = _load("RULE-M05", "after")
        assert m.input_shape[0] == 1

    def test_transform_fixes_batch_size(self):
        from optimizer.transforms import fix_batch_size
        before = _load("RULE-M05", "before")
        transformed = fix_batch_size(before)
        assert transformed.input_shape[0] == 1


# ---------------------------------------------------------------------------
# RULE-M06 — Activation fusion
# ---------------------------------------------------------------------------

class TestRuleM06:
    def test_before_has_standalone_activation(self):
        m = _load("RULE-M06", "before")
        assert any(type(l).__name__ in ("Activation", "ReLU") for l in m.layers)
        conv = m.get_layer("conv1")
        assert _activation_of(conv) in ("linear", "none", "")

    def test_after_has_fused_activation(self):
        m = _load("RULE-M06", "after")
        assert not any(type(l).__name__ in ("Activation", "ReLU") for l in m.layers
                       if l.name not in ("input", "gap"))
        conv = m.get_layer("conv1")
        assert _activation_of(conv) == "relu"

    def test_transform_fuses_activation(self):
        from optimizer.transforms import apply_cascading_optimizations
        before = _load("RULE-M06", "before")
        transformed = apply_cascading_optimizations(before)
        # The standalone relu1 layer should no longer exist.
        assert not any(l.name == "relu1" for l in transformed.layers)


# ---------------------------------------------------------------------------
# RULE-M06.1 — Fold MaxPool into strided conv
# ---------------------------------------------------------------------------

class TestRuleM06_1:
    def test_before_has_maxpool(self):
        m = _load("RULE-M06.1", "before")
        assert any(isinstance(l, tf.keras.layers.MaxPooling2D) for l in m.layers)

    def test_after_has_no_maxpool(self):
        m = _load("RULE-M06.1", "after")
        assert not any(isinstance(l, tf.keras.layers.MaxPooling2D) for l in m.layers)

    def test_after_conv_has_stride_2(self):
        m = _load("RULE-M06.1", "after")
        conv = m.get_layer("conv1")
        assert tuple(conv.strides) == (2, 2)

    def test_transform_removes_maxpool(self):
        from optimizer.transforms import fold_maxpool_into_strided_conv
        before = _load("RULE-M06.1", "before")
        transformed = fold_maxpool_into_strided_conv(before)
        assert not any(isinstance(l, tf.keras.layers.MaxPooling2D) for l in transformed.layers)


# ---------------------------------------------------------------------------
# RULE-M06.2 — Bilinear Resizing → Conv2DTranspose
# ---------------------------------------------------------------------------

class TestRuleM06_2:
    def test_before_has_resizing(self):
        m = _load("RULE-M06.2", "before")
        assert any(type(l).__name__ == "Resizing" for l in m.layers)

    def test_after_has_conv2dtranspose(self):
        m = _load("RULE-M06.2", "after")
        assert any(isinstance(l, tf.keras.layers.Conv2DTranspose) for l in m.layers)
        assert not any(type(l).__name__ == "Resizing" for l in m.layers)

    def test_transform_replaces_resizing(self):
        from optimizer.transforms import replace_bilinear_resize_with_conv2dtranspose
        before = _load("RULE-M06.2", "before")
        transformed = replace_bilinear_resize_with_conv2dtranspose(before)
        assert not any(type(l).__name__ == "Resizing" for l in transformed.layers)
        assert any(isinstance(l, tf.keras.layers.Conv2DTranspose) for l in transformed.layers)


# ---------------------------------------------------------------------------
# RULE-M06.3 — Split + Concat collapse
# ---------------------------------------------------------------------------

class TestRuleM06_3:
    def test_before_concat_has_more_inputs(self):
        m = _load("RULE-M06.3", "before")
        concat = m.get_layer("concat1")
        n_before = len(concat._inbound_nodes[0].keras_inputs)
        after = _load("RULE-M06.3", "after")
        concat_a = after.get_layer("concat1")
        n_after = len(concat_a._inbound_nodes[0].keras_inputs)
        assert n_before > n_after

    def test_after_concat_input_count(self):
        m = _load("RULE-M06.3", "after")
        concat = m.get_layer("concat1")
        assert len(concat._inbound_nodes[0].keras_inputs) == 2


# ---------------------------------------------------------------------------
# RULE-M06.4 — Residual Add operand reorder
# ---------------------------------------------------------------------------

class TestRuleM06_4:
    def test_before_shortcut_at_index_0(self):
        """Before: Add([shortcut=inp, conv_out]) — shortcut at index 0."""
        m = _load("RULE-M06.4", "before")
        add = m.get_layer("add1")
        node = add._inbound_nodes[0]
        producers = [t._keras_history.layer for t in node.keras_inputs]
        assert producers[0].name == "input"    # shortcut branch

    def test_after_conv_at_index_0(self):
        """After: Add([conv_out, shortcut]) — conv result at index 0."""
        m = _load("RULE-M06.4", "after")
        add = m.get_layer("add1")
        node = add._inbound_nodes[0]
        producers = [t._keras_history.layer for t in node.keras_inputs]
        assert producers[0].name == "conv1"    # conv branch


# ---------------------------------------------------------------------------
# RULE-M06.5 — In-place concat (not yet implemented)
# ---------------------------------------------------------------------------

class TestRuleM06_5:
    def test_fixtures_exist(self):
        _load("RULE-M06.5", "before")
        _load("RULE-M06.5", "after")

    def test_before_has_concat(self):
        m = _load("RULE-M06.5", "before")
        assert any(isinstance(l, tf.keras.layers.Concatenate) for l in m.layers)
